FROM rockylinux:latest
RUN yum update -y && yum install -y httpd && yum clean all
#RUN echo "Webserver is running" > /var/www/html/index.html
RUN rm -rf  /etc/httpd/conf.d/welcome.conf
EXPOSE 80
CMD /usr/sbin/httpd -D FOREGROUND
