---

  -  name: creating vm role start
     hosts: proxmox
     user: root
     vars_prompt:
       - name: nazwa
         prompt: provide vm name
         private: no
       - name: vm_uid
         prompt: provide vm uid
         private: no
     gather_facts: false
     roles: 
       -  proxmox_vm_create
     tasks:
       -  name: start created vm
          community.general.proxmox_kvm:
            api_user: "{{ api_user}}"
            api_password: "{{ api_password }}"
            api_host: "{{ api_host }}"
            name: "{{ nazwa }}"
            node: "{{ node }}"
            state: started



  
     

               
