---


  -  name: config created vm start
     hosts: new
     user: root
     vars_prompt:
       -  name: vm_hostname
          prompt: provide vm new hostname
          private: no
          #    -  name: vm
          # prompt: provide name where to start playbook
          #private: no
     roles:
       -  proxmox_config_vm


  -  name: db2 query tasks phase
     hosts: db
     gather_facts: no
     tasks:
       -  name: query for first free ip
          postgresql_query:
            db: ipki
            query: SELECT ip1 FROM ipki WHERE used = 'n' LIMIT 1
            login_user: postgres
            login_password: tomek211
          register: query_output
          become: yes
          become_user: postgres

       -  name: debug - and get ip from output
          debug:
            msg: "{{ query_output.query_result[0]['ip1'] }}"
          
   
       -  name: set selected ip  as used
          postgresql_query:
            db: ipki
            query: UPDATE ipki SET used = 'y' WHERE ip1 = %(ipek)s
            named_args: 
              ipek: "{{ query_output.query_result[0]['ip1']}}"
            login_user: postgres
            login_password: tomek211
          become: true
          become_user: postgres

       - name: copy ip to file
         copy:
           content: "{{ query_output.query_result[0]['ip1'] }}"
           dest: /tmp/ipek.txt

       -  name: fetch ip file
          fetch:
            src: /tmp/ipek.txt
            dest: ipek.txt
            flat: yes
        

  -  name: setup new ip on newhost
     hosts: new
     gather_facts: no
     become: true
     vars:
       ipek: "{{ lookup('file','ipek.txt')}}"
     tasks:
       -  name: modify ip
          nmcli:
            conn_name: ens18
            type: ethernet
            state: present
            ip4: "{{ ipek }}"
       - name: reboot 
         reboot:
           reboot_timeout: 180  
          
