---

   -  name: setting all vms
      hosts: "{{ hosts_prompt }}"
      vars_prompt:
        - name: hosts_prompt
          prompt: provide hosts or group to execute vm setup play
          private: no
      user: root
      become: true
      roles:
        - vmsetup
