---


       -  name: add docker repo
          yum_repository:
            name: docker
            description: docker-repo
            file: docker
            baseurl: "{{ repo_url }}"
            gpgcheck: no

       -  name: perform podman check
          command: "rpm -qa | grep podman"
          register: podman_check
          ignore_errors: true

       -  name: install docker with allowerasing
          command: "yum install docker-ce --allowerasing -y"
          when: "'podman' in podman_check.stdout"
          register: install_command_result

       -  name: install docker as no podman present
          yum:
            name: "{{ item }}"
            state: latest
          loop:
            - docker-ce
            - docker-ce-cli
            - containerd
          when: install_command_result.skipped

       -  name: start and enable docker service
          service:
            name: docker
            state: started
            enabled: true
          become: yes

       -  name: add user ansible to docker group
          user:
            name: "{{ user_to_add }}"
            groups: "{{ add_to_group }}"
            append: yes


       -  name: install docker sdk for python
          command: "pip3 install docker-py"
