---
# tasks file for proxmox_config_vm


  -  name: setup new vm -set default multi-user target
     file:
       src: /usr/lib/systemd/system/multi-user.target
       dest: /etc/systemd/system/default.target
       state: link
  -  name: epel installed
     yum:
       name: epel-release
       state: present
  -  name: user add tomek
     user:
       name: tomek
       state: present
       password: "{{ 'tomek211' | password_hash('sha512') }}"
  -  name: set sshd keys
     authorized_key:
       user: tomek
       state: present
       key: "{{ lookup('file','/home/tomek/.ssh/id_rsa.pub') }}"
  -  name: add user tomek to sudoers
     copy:
       content: " %tomek ALL=(ALL) NOPASSWD: ALL"
       dest: /etc/sudoers.d/tomek

  -  name: update system
     yum:
       name: "*"
       state: latest

  -  name: install packages
     yum:
       name:
         - python3
         - tree
         - cockpit
         - fail2ban
         - wget
         - ntfs-3g
         - vim
         - net-tools
         - yum-utils
         - qemu-guest-agent
         - lvm2


       state: latest

  -  name: enable cockpit service
     systemd:
       name: "cockpit.socket"
       enabled: true
       state: started

  -  name: set firewall for cockpit
     firewalld:
       service: cockpit
       state: enabled
       permanent: yes

  -  name: copy fail2ban config to local
     template:
       src: jail.local.j2
       dest: /etc/fail2ban/jail.local
       owner: root
       group: root
       mode: 0644

  -  name: fail2ban enable and start
     service:
       name: fail2ban
       state: started
       enabled: true

  -  name: sshd restart
     service:
       name: sshd
       state: restarted


       #-  name: create hostname file
    #copy:
    #  dest: /tmp/hostfile
    #content: "{{ vm_hostname }}"

       #-  name: copy hostfile to local
       #fetch:
       #src: /tmp/hostfile
       #dest: /tmp/hostfile
       #flat: yes
