---


  -  name: config created vm start
     hosts: all
     become: true
          #    -  name: vm
          # prompt: provide name where to start playbook
          #private: no
     tasks:
       -  name: setup new vm -set default multi-user target
          file:
            src: /usr/lib/systemd/system/multi-user.target
            dest: /etc/systemd/system/default.target
            state: link


       -  name: epel installed
          yum:
            name: epel-release
            state: present

       -  name: clean cache
          command: "yum clean all"

       -  name: update system
          yum:
            name: "*"
            state: latest
       -  name: user add tomek
          user:
            name: tomek
            state: present
            password: "{{ 'tomek211' | password_hash('sha512') }}"

       -  name: set sshd keys
          authorized_key:
            user: tomek
            state: present
            key: "{{ lookup('file','/home/tomek/.ssh/id_rsa.pub') }}"
       -  name: add user tomek to sudoers
          copy:
            content: " %tomek ALL=(ALL) NOPASSWD: ALL"
            dest: /etc/sudoers.d/tomek
       -  name: set timezone to Europe/Warsaw
          timezone:
            name: Europe/Warsaw


       -  name: install packages
          yum:
            name:
              - python3
              - tree
              - cockpit
              - wget
    #          - ntfs-3g
              - vim
              - firewalld
              - net-tools
              - yum-utils
              - qemu-guest-agent
              - lvm2


            state: latest

       -  name: enable cockpit service
          systemd:
            name: "cockpit.socket"
            enabled: true
            state: started

       -  name: set firewall for cockpit
          firewalld:
            service: cockpit
            state: enabled
            permanent: yes


       -  name: sshd restart
          service:
            name: sshd
            state: restarted
